# Generated by Django 3.1.7 on 2021-03-16 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ask_expert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expert_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('question', models.CharField(max_length=500)),
                ('answer', models.CharField(max_length=500)),
                ('dt', models.CharField(max_length=50)),
                ('tm', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='crop_master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_type_id', models.IntegerField()),
                ('crop_name', models.CharField(max_length=50)),
                ('crop_sname', models.CharField(max_length=50)),
                ('crop_descp', models.CharField(max_length=500)),
                ('crop_area', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='crop_pics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_id', models.IntegerField()),
                ('pic_path', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='crop_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='crop_variety',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_id', models.IntegerField()),
                ('variety_name', models.CharField(max_length=50)),
                ('variety_sname', models.CharField(max_length=50)),
                ('crop_descp', models.CharField(max_length=500)),
                ('crop_area', models.CharField(max_length=250)),
                ('pic_path', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='cultivation_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_id', models.IntegerField()),
                ('land_type', models.CharField(max_length=500)),
                ('soil_concentration', models.CharField(max_length=500)),
                ('descp', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='cultivation_pics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cultivation_id', models.IntegerField()),
                ('pic_path', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='disease_master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_id', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('descrp', models.CharField(max_length=250)),
                ('pic_path', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='expert_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=250)),
                ('status', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('descp', models.CharField(max_length=500)),
                ('dt', models.CharField(max_length=50)),
                ('tm', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='fertilizer_master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_id', models.IntegerField()),
                ('f_type', models.CharField(max_length=25)),
                ('f_name', models.CharField(max_length=50)),
                ('descp', models.CharField(max_length=250)),
                ('image', models.CharField(max_length=25)),
                ('application', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='pesticides_master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_id', models.IntegerField()),
                ('pt_type', models.CharField(max_length=25)),
                ('product_name', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=25)),
                ('descp', models.CharField(max_length=250)),
                ('application', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='user_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('kcno', models.IntegerField()),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=25)),
                ('age', models.IntegerField()),
                ('addr', models.CharField(max_length=500)),
                ('pin', models.CharField(max_length=25)),
                ('contact', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=250)),
                ('status', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='user_login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=100)),
                ('passwd', models.CharField(max_length=25)),
                ('u_type', models.CharField(max_length=10)),
            ],
        ),
    ]
