# Generated by Django 3.1.7 on 2021-03-16 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_expert_details_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cultivation_details',
            name='pic_path',
            field=models.CharField(default='none', max_length=50),
            preserve_default=False,
        ),
    ]
