# Generated by Django 3.1.7 on 2021-03-16 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_cultivation_details_pic_path'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cultivation_pics',
        ),
    ]
