# Generated by Django 3.2 on 2021-05-04 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_delete_cultivation_pics'),
    ]

    operations = [
        migrations.CreateModel(
            name='seller_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=200)),
                ('addr', models.CharField(max_length=500)),
                ('pin', models.CharField(max_length=25)),
                ('contact', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=250)),
                ('status', models.CharField(max_length=25)),
            ],
        ),
    ]
