# Generated by Django 3.2 on 2021-05-06 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_seller_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_id', models.IntegerField()),
                ('p_name', models.CharField(max_length=50)),
                ('descp', models.CharField(max_length=250)),
                ('price', models.CharField(max_length=25)),
                ('image', models.CharField(max_length=25)),
            ],
        ),
    ]
